# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bZilIqIaIM4CcfF2R_dA3sTd9icNSsn
"""



import zipfile
import os

# Define paths
zip_path = "drive/MyDrive/archive.zip"  # Path to your ZIP file
extract_path = "/content/drive/My Drive/extracted_data"  # Destination folder in Google Drive

# Ensure the destination folder exists
os.makedirs(extract_path, exist_ok=True)

# Extract the ZIP file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(f"Files extracted to: {extract_path}")



import os
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix

# Set dataset path
dataset_path = "drive/MyDrive/extracted_data/trash_images"

# Image parameters
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 25  # Increase epochs

# **Enhanced Data Augmentation**
datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.3,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.15
)

train_data = datagen.flow_from_directory(
    dataset_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

test_data = datagen.flow_from_directory(
    dataset_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

# Get class labels
class_labels = list(train_data.class_indices.keys())

# **Class Weights Calculation**
labels = train_data.classes
class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)
class_weight_dict = {i: class_weights[i] for i in range(len(class_labels))}

# **Load MobileNetV2 with Partial Fine-Tuning**
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# **Unfreeze Last Few Layers for Fine-Tuning**
for layer in base_model.layers[-20:]:
    layer.trainable = True  # Allow fine-tuning

# **Build Enhanced Model**
model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(256, activation='relu'),
    Dropout(0.4),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(len(class_labels), activation='softmax')
])

# **Compile Model with AdamW Optimizer**
model.compile(optimizer=tf.keras.optimizers.AdamW(learning_rate=0.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# **Callbacks**
checkpoint_filepath = "drive/MyDrive/best_trash_model.weights.h5"
ES = EarlyStopping(monitor='val_loss', mode='min', patience=7, restore_best_weights=True)
RLROP = ReduceLROnPlateau(monitor='val_loss', patience=4, factor=0.2, min_lr=1e-6)
MCH = ModelCheckpoint(checkpoint_filepath, save_best_only=True, save_weights_only=True)

# **Resume Training if Checkpoint Exists**
if os.path.exists(checkpoint_filepath):
    model.load_weights(checkpoint_filepath)
    print("Resuming training from checkpoint...")

# **Custom TQDM Progress Bar Callback**
class TQDMProgress(tf.keras.callbacks.Callback):
    def on_epoch_begin(self, epoch, logs=None):
        self.epoch_progress = tqdm(total=len(train_data), desc=f"Epoch {epoch+1}/{EPOCHS}", position=0, leave=True)

    def on_batch_end(self, batch, logs=None):
        self.epoch_progress.update(1)

    def on_epoch_end(self, epoch, logs=None):
        self.epoch_progress.close()
        print(f"\n🔹 Epoch {epoch+1}/{EPOCHS} - Loss: {logs['loss']:.4f}, Accuracy: {logs['accuracy']:.4f}, "
              f"Val Loss: {logs['val_loss']:.4f}, Val Accuracy: {logs['val_accuracy']:.4f}")

# **Train Model**
history = model.fit(train_data, epochs=EPOCHS, validation_data=test_data,
                    class_weight=class_weight_dict, callbacks=[ES, RLROP, MCH, TQDMProgress()])

# **Save Final Model**
model.save("drive/MyDrive/final_trash.keras")
print("Model saved successfully.")

# **Evaluation**
print("\n🔍 Evaluating Model...")
model = load_model("drive/MyDrive/final_trash.keras")

# **Get Predictions**
predictions = model.predict(test_data)
y_pred = np.argmax(predictions, axis=1)
y_true = test_data.classes

# **Classification Report**
print("\n📊 Classification Report:")
print(classification_report(y_true, y_pred, target_names=class_labels))

# **Confusion Matrix**
conf_matrix = confusion_matrix(y_true, y_pred)

# **Plot Confusion Matrix**
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# **Plot Accuracy & Loss**
accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs_range = range(1, len(accuracy) + 1)

plt.figure(figsize=(12, 5))

# Accuracy Plot
plt.subplot(1, 2, 1)
plt.plot(epochs_range, accuracy, 'b', label='Train Accuracy')
plt.plot(epochs_range, val_accuracy, 'r', label='Test Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss Plot
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, 'b', label='Train Loss')
plt.plot(epochs_range, val_loss, 'r', label='Test Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

